"use client";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import * as React from "react";
import Link from "next/link";
import { Checkbox } from "@/components/ui/checkbox";
import { useState } from "react";
import { Spinner } from "@/components/ui/spinner";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";

const tickets = [
  {
    id: 1,
    date: "06/01/2024 10:12 AM",
    source: "customer",
    summary: "Order stuck in processing for 5 days",
    priority: "high",
    text: "Hi, I ordered replacement filters (order #98421) on May 27th and the status still says 'processing'. The estimated delivery was 2–3 days. Can you check if there's an issue with my order?",
  },
  {
    id: 2,
    date: "06/02/2024 08:45 AM",
    source: "employee",
    summary: "VPN disconnecting every few minutes",
    priority: "high",
    text: "Since yesterday my VPN disconnects every 5 minutes. I'm getting kicked out of our internal dashboard and Teams calls. I restarted my laptop but the issue continues. – Alex, Sales",
  },
  {
    id: 3,
    date: "06/03/2024 02:30 PM",
    source: "system",
    summary: "System alert: checkout-service error rate elevated",
    priority: "high",
    text: "Alert generated by monitoring: checkout-service error_rate=3.7% (>3.0%) for 10 minutes in region eu-west at 2024-06-03T14:18Z.",
  },
  {
    id: 4,
    date: "06/04/2024 09:05 AM",
    source: "customer",
    summary: "Password reset link not working",
    priority: "medium",
    text: "Hello support, I'm trying to reset my password but the link sent to me immediately says 'token expired'. I've tried three times. Can someone help?",
  },
  {
    id: 5,
    date: "06/04/2024 11:20 AM",
    source: "employee",
    summary: "Employee laptop freezing randomly",
    priority: "medium",
    text: "My company laptop freezes 2–3 times per day and requires a forced restart. This started after the latest Windows update. Please advise. – Rachel, Finance",
  },
  {
    id: 6,
    date: "06/05/2024 01:10 PM",
    source: "system",
    summary: "Billing discrepancy for monthly subscription",
    priority: "low",
    text: "I was charged $79 this month instead of the usual $59. I haven't upgraded my plan. Can you explain the extra charge? – Customer: John M.",
  },
  {
    id: 7,
    date: "06/06/2024 03:40 PM",
    source: "customer",
    summary: "HR portal access denied",
    priority: "medium",
    text: "I cannot log in to the HR portal. It keeps showing 'Access Denied – Missing role: employee.basic'. This started today after onboarding a new system.",
  },
  {
    id: 8,
    date: "06/07/2024 07:55 AM",
    source: "system",
    summary: "Shipping delay for international order",
    priority: "low",
    text: "Order #109233 shipped on May 29th but hasn’t updated since June 1st. Tracking page just says 'In transit – awaiting customs clearance'. Is this normal?",
  },
  {
    id: 9,
    date: "06/08/2024 04:12 PM",
    source: "employee",
    summary: "Internal service outage - metrics-service",
    priority: "high",
    text: "System alert: metrics-service latency spike detected. p95 latency > 1200ms for 15 minutes. Region: us-central. Impact: dashboard loading times degraded.",
  },
  {
    id: 10,
    date: "06/09/2024 09:50 AM",
    source: "customer",
    summary: "Multi-factor authentication failing",
    priority: "high",
    text: "I can't log in because the SMS code never arrives. I tried 4 times. Can someone from the Identity team check if there's an issue with SMS delivery?",
  },
];

type TicketForInsight = {
  id: number;
  date: string;
  source: string;
  summary: string;
  priority: string;
  text: string;
};

function InsightsPage() {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [selectedTicketData, setSelectedTicketData] = useState<
    TicketForInsight[]
  >([]);
  const [selectedTickets, setSelectedTickets] = useState<number[]>([]);
  const [specificTickets, setSpecificTickets] = useState({
    priority: "",
    source: "",
    quantity: "",
  });

  const handleAIInsightCheckbox = async (
    selectedTicketData: TicketForInsight[]
  ) => {
    setLoading(true);

    try {
      const response = await fetch("/api/generate-insight", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ tickets: selectedTicketData }),
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Request failed");
      }

      const data = await response.json();
      setResult(data);
      console.log("AI Result:", data);
    } catch (err: any) {
      setError(err.message || "Something went wrong");
    } finally {
      setLoading(false);
    }
    // console.log("Selected tickets:", selectedTickets);
  };

  const handleAIInsightSpecific = async (
    selectedTicketData: TicketForInsight[]
  ) => {
    setLoading(true);

    try {
      const response = await fetch("/api/generate-insight", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ tickets: selectedTicketData }),
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Request failed");
      }

      const data = await response.json();
      setResult(data);
      console.log("AI Result:", data);
    } catch (err: any) {
      setError(err.message || "Something went wrong");
    } finally {
      setLoading(false);
    }
    // console.log("Selected tickets:", selectedTickets);
  };

  const handleCheckboxList = async () => {
    //Study better
    const selectedTicketData = tickets.filter((ticket) =>
      selectedTickets.includes(ticket.id)
    );
    //console.log("Selected Ticket Data:", selectedTicketData);

    // setLoading(true);

    handleAIInsightCheckbox(selectedTicketData);
  };

  const handleSpecificList = () => {
    // Study better this filtering
    const results = tickets
      .filter((ticket) => {
        return (
          (!specificTickets.priority ||
            ticket.priority === specificTickets.priority) &&
          (!specificTickets.source || ticket.source === specificTickets.source)
        );
      })
      .slice(0, Number(specificTickets.quantity) || tickets.length);

    handleAIInsightSpecific(results);

    //console.log("Filtered tickets:", results);
  };

  return (
    <div>
      <Breadcrumb>
        <BreadcrumbList>
          <BreadcrumbItem>
            <BreadcrumbLink href="/dashboard">Dashboard</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbPage>Insight Page</BreadcrumbPage>
          </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>
      <h1>Insight Page</h1>
      <Link href="/pastInsights">Go to Past Insights</Link>
      <div>
        <ScrollArea className="h-[40vh] w-full rounded-md border">
          <div className="p-4">
            {/* <h4 className="mb-4 text-sm leading-none font-medium">Recent</h4> */}
            <div className="grid grid-cols-5 w-full items-center gap-4">
              <div>
                <h5 className="mb-4 text-sm leading-none font-medium">
                  Checkbox
                </h5>
              </div>
              <div>
                <h5 className="mb-4 text-sm leading-none font-medium">
                  Priority
                </h5>
              </div>
              <div>
                <h5 className="mb-4 text-sm leading-none font-medium">
                  Summary
                </h5>
              </div>
              <div>
                <h5 className="mb-4 text-sm leading-none font-medium">Date</h5>
              </div>
            </div>

            {tickets.map(({ id, priority, date, summary }) => (
              <React.Fragment key={id}>
                <div className="grid grid-cols-5 w-full items-center gap-4">
                  <div>
                    {/* Study this better */}
                    <Checkbox
                      onClick={() =>
                        setSelectedTickets((prev) =>
                          prev.includes(id)
                            ? prev.filter((ticketId) => ticketId !== id)
                            : [...prev, id]
                        )
                      }
                    />
                  </div>
                  <div>
                    <p>{priority}</p>
                  </div>
                  <div>
                    <p>{summary}</p>
                  </div>
                  <div>
                    <p>{date}</p>
                  </div>
                  <div>
                    <Link href={`tickets/${id}`}>View</Link>
                  </div>
                </div>
                <Separator className="my-2" />
              </React.Fragment>
            ))}
          </div>
        </ScrollArea>
        <Button
          onClick={handleCheckboxList}
          disabled={selectedTickets.length === 0}
        >
          Generate AI Insight
        </Button>
      </div>

      <div className="flex space-x-[4vw] mb-4 mt-20">
        <Select
          onValueChange={(value) =>
            setSpecificTickets({ ...specificTickets, priority: value })
          }
        >
          <SelectTrigger className="w-[10vw]">
            <SelectValue placeholder="Priority" />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectLabel>Priority</SelectLabel>
              <SelectItem value="low">low</SelectItem>
              <SelectItem value="medium">medium</SelectItem>
              <SelectItem value="high">high</SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
        <Select
          onValueChange={(value) =>
            setSpecificTickets({ ...specificTickets, source: value })
          }
        >
          <SelectTrigger className="w-[10vw]">
            <SelectValue placeholder="Source" />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectLabel>Source</SelectLabel>
              <SelectItem value="customer">Costumer</SelectItem>
              <SelectItem value="employee">Employee</SelectItem>
              <SelectItem value="system">System</SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
        <Input
          value={specificTickets.quantity}
          onChange={(e) =>
            setSpecificTickets({ ...specificTickets, quantity: e.target.value })
          }
          className="w-[10vw]"
          placeholder="Quantity"
        />
        <Button
          onClick={handleSpecificList}
          disabled={
            specificTickets.priority === "" || specificTickets.source === ""
          }
        >
          Generate AI Insight
        </Button>
      </div>
      <div>
        <h1>Result</h1>
        <div>
          {error && <p className="text-red-500 mb-4">{error}</p>}
          {loading && <Spinner className="size-8" />}
          {result && (
            <div className="border rounded p-4 space-y-2">
              <h2 className="font-semibold">AI Analysis</h2>
              <p>
                <b>Date:</b> {result.date}
              </p>
              <p>
                <b>Overall Summary:</b> {result.overallSummary}
              </p>
              <p>
                <b>Recurring Issues:</b> {result.recurringIssues}
              </p>
              <p>
                <b>Automation Ideas:</b> {result.automationIdeas}
              </p>
              <p>
                <b>Suggested Faqs:</b> {result.suggestedFaqs}
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default InsightsPage;
